image: python:3.10

stages:
  - lint
  - test

before_script:
  - pip install ruff pytest pytest-cov
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - ruff check .
    - ruff format --check .

test:
  stage: test
  script:
    - pytest --cov=./
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
